id: AAD91ACB4
title: 'The Melody of Complete Accomplishment: A Prayer to Those Praised as Ornaments
  of the Practice Lineage'
type: translation
pechas:
- I627D9DD2
- I16000F5C
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:56:06.199132
  last_modified_at: 2023-01-04 11:56:06.199147
  collections:
  - Gampopa Series
  - Works of Tibetan Masters
alignment_to_base:
  I627D9DD2/4EAC: F136
  I16000F5C/488D: F136
